# Generated by Django 3.0.8 on 2020-07-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=300)),
                ('post_date', models.DateTimeField()),
                ('post_text', models.TextField()),
                ('post_image', models.ImageField(upload_to='posts_image/')),
            ],
        ),
    ]
